version: '3'
services:
  postgres: 
    image: 'postgres:16'
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: 'redis:7'
    restart: unless-stopped
  api:
    image: amiitdeshmukhcctech/fibo-server
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  fibbonachi:
    image: amiitdeshmukhcctech/fibo-client
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  worker:
    image: amiitdeshmukhcctech/fibo-worker
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432  
  nginx:
    image: amiitdeshmukhcctech/fibo-nginx
    restart: always
    ports:
      - '8080:80'
    
volumes:
  postgres_data: