name: Fibo

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: cd worker && npm install

      - name: Run tests
        run: cd worker && npm test
  
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Login to Docker hub
        run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin

      - name: Build images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fibo-worker ./worker
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fibo-server ./server
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fibo-nginx ./nginx
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fibo-client ./fibbonachi

      - name: Push Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/fibo-worker
          docker push ${{ secrets.DOCKER_USERNAME }}/fibo-server
          docker push ${{ secrets.DOCKER_USERNAME }}/fibo-nginx
          docker push ${{ secrets.DOCKER_USERNAME }}/fibo-client

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USER}}
          key: ${{secrets.EC2_SSH_KEY}}
          script: |
            cd ~/app
            docker compose pull
            docker compose up -d
